const { chromium } = require('../../apps/keyword-rank/node_modules/playwright-core');
const fs = require('fs'), path = require('path'), assert = require('node:assert/strict');
const { pathToFileURL } = require('url');
const release = path.resolve(process.argv[2]);
const output = path.resolve('work/product-image-qa'); fs.mkdirSync(output, {recursive:true});
(async () => {
 const browser = await chromium.launch({channel:'msedge', headless:true});
 const page = await browser.newPage({viewport:{width:1536,height:960}});
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 const shot = name=>page.screenshot({path:path.join(output,name+'.png')});
 const open = async()=>{await page.locator('.model-icon').first().click();await page.locator('.product-gallery').waitFor();};
 try {
 await page.goto(pathToFileURL(path.join(release,'index.html')).href);
 await page.locator('.model-icon').first().waitFor({timeout:60000});
 await page.getByRole('button',{name:'暂时跳过',exact:true}).click({timeout:15000});
 await page.waitForTimeout(1000);
 const icon=page.locator('.model-icon').first();
 await icon.hover(); await page.locator('.product-image-preview.is-visible').waitFor();
 await page.locator('.product-image-preview > button').hover();await page.waitForTimeout(300);
 assert(await page.locator('.product-image-preview.is-visible').isVisible()); const hoverBox=await page.locator('.product-image-preview').boundingBox(), sideBox=await page.locator('.sidebar').boundingBox(); assert(hoverBox.x>=sideBox.x+sideBox.width, 'preview stays outside sidebar text'); await shot('hover');
 await page.locator('.product-image-preview > button').dblclick();await page.locator('.product-gallery').waitFor();await page.waitForTimeout(450);
 await shot('gallery-initial');
 await page.getByRole('button',{name:'选择简略图标',exact:true}).click();
 await page.locator('.product-gallery .apparel-icon-grid button').nth(1).click();
 await page.locator('.product-gallery').waitFor({state:'detached'});
 await open();assert.equal(await page.locator('.product-image-history button').count(),2);
 const png=fs.readdirSync(path.join(release,'assets')).find(n=>n.startsWith('sweater-')&&n.endsWith('.png'));
 await page.locator('.product-gallery input[type=file]').setInputFiles(path.join(release,'assets',png));
 await page.locator('.product-gallery').waitFor({state:'detached'});
 await page.reload();await icon.waitFor(); await page.waitForTimeout(500);await open();
 assert.equal(await page.locator('.product-image-history button').count(),3);
 const source = await icon.locator('img').getAttribute('src');assert(source.startsWith('data:image/'));
 await page.waitForTimeout(450);await shot('gallery-history');
 const stacked=page.locator('.product-image-card.stacked').last(); const sb=await stacked.boundingBox(); await page.mouse.click(sb.x+sb.width/2,sb.y+8); assert((await page.locator('.product-image-card.front span').textContent()).includes('仅查看')); await page.getByRole('button',{name:'选择当前图片',exact:true}).click();
 await page.getByRole('button',{name:'选择历史图片 1',exact:true}).click();
 assert((await page.locator('.product-image-card.front span').textContent()).includes('仅查看'));
 assert.equal(await icon.locator('img').getAttribute('src'),source);
 await shot('history-selected');
 await page.keyboard.press('Escape');await page.locator('.product-gallery').waitFor({state:'detached'});
 await icon.hover();await page.locator('.product-image-preview.is-visible').waitFor();
 await page.mouse.move(1000,900);await page.waitForTimeout(550);assert.equal(await page.locator('.product-image-preview').count(),0);
 await page.setViewportSize({width:1100,height:720});await open();await page.waitForTimeout(450);
 const bounds=await page.locator('.product-gallery').boundingBox();assert(bounds.y>=0&&bounds.y+bounds.height<=720);
 await shot('compact-gallery');
 assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(output,'result.json'),JSON.stringify({ok:true,checks:['hover bridge','double click','icon selection','custom upload','history after reload','history read only','fade dismissal','compact layout'],errors},null,2));
 console.log('PASS product gallery QA');
 } catch(e) {await shot('failure');throw e;} finally {await browser.close();}
})();
