import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, ShieldCheck, Settings2, Upload, Sparkles, X, History, FileSearch, CheckCircle2, AlertCircle, LoaderCircle } from 'lucide-react';
import { FIELDS, LABELS, TYPES, shift } from '../ai/core.mjs';
import './AIWorkspace.css';
import './AIKeywordActions.css';

const api=()=>window.keywordAI;
const today=()=>new Date().toLocaleDateString('en-CA');
const show=(n,percent=false)=>n==null?'—':percent?`${(n*100).toFixed(2)}%`:Number(n).toLocaleString('zh-CN',{maximumFractionDigits:2});
const numberFields=['impressions','clicks','spend','orders','sales'];
function MetricTable({evidence,sources,highlight}) {
  return <div className="ai-table-scroll"><table className="ai-evidence"><thead><tr><th>证据 / 关键词</th><th>范围与来源</th><th>自然排名</th><th>SP 排名</th><th>曝光</th><th>点击</th><th>花费</th><th>订单</th><th>销售额</th><th>ACOS</th><th>数据状态</th></tr></thead><tbody>{evidence.map(e=><tr key={e.id} id={`ai-${e.id}`} className={highlight===e.id?'ai-highlight':''}><td><b>{e.id}</b><span>{e.keyword}</span></td><td>{e.kind==='rank'?'第三方排名快照':'所选广告组整体'}<details><summary>查看来源</summary><pre>{JSON.stringify(sources?.[e.id],null,2)}</pre></details></td><td>{e.kind==='rank'?`${show(e.current.naturalRank.first)} → ${show(e.current.naturalRank.last)}`:'—'}</td><td>{e.kind==='rank'?`${show(e.current.spRank.first)} → ${show(e.current.spRank.last)}`:'—'}</td>{numberFields.map(k=><td key={k}>{e.kind==='ads'?show(e.current[k]):'—'}</td>)}<td>{e.kind==='ads'?show(e.current.acos,true):'—'}</td><td>{e.kind==='rank'?`${e.current.observedDays} 个观测日`:e.coverage.attributionMature?'归因窗口已过，仍可能修订':'归因尚未完整'}<details><summary>本期 / 前期指标</summary><pre>{JSON.stringify({current:e.current,previous:e.previous,coverage:e.coverage},null,2)}</pre></details></td></tr>)}</tbody></table></div>;
}

function ImportPanel({onChanged,onError}) {
  const [file,setFile]=useState(null),[mapping,setMapping]=useState({}),[preview,setPreview]=useState(null),[working,setWorking]=useState(false);
  const [meta,setMeta]=useState({type:'search',account:'',accountType:'',marketplace:'CA',currency:'CAD',timezone:'America/Toronto',numberFormat:'dot',asOf:today()});
  const update=(key,value)=>{setMeta(m=>({...m,[key]:value}));setPreview(null);};
  const run=async fn=>{onError('');setWorking(true);try{await fn();}catch(e){onError(e.message);}finally{setWorking(false);}};
  return <section className="ai-section"><div className="ai-section-heading"><div><h2>导入 SP 广告报表</h2><p>文件在本机解析，原文件保持不变。先核对字段和口径，再保存。</p></div><button className="ai-primary" disabled={working} onClick={()=>run(async()=>{const f=await api().pickReport();if(f){setFile(f);setMapping(f.mapping);setPreview(null);setMeta(m=>({...m,asOf:f.asOf}));}})}><Upload size={16}/>选择 CSV / XLSX</button></div>
  {!file?<div className="ai-empty"><FileSearch size={34}/><h3>从 Amazon Ads 下载报表后导入</h3><p>支持搜索词、投放、推广商品三类 SP 报表。优先选择“每天”，便于比较和更新归因数据。</p><p>每个文件一个数据工作表，最多 20 MB、50,000 行。多币种、账户或站点请分别导出。</p></div>:<>
  <div className="ai-notice"><FileSearch size={18}/><span><b>{file.filename}</b> · {file.count.toLocaleString()} 行。请确认文件仅包含下方账户、站点和 SP 广告数据。</span></div>
  <div className="ai-form-grid"><label>报表类型<select value={meta.type} onChange={e=>update('type',e.target.value)}>{Object.entries(TYPES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>本地账户代号<input value={meta.account} placeholder="例如：加拿大店铺 A" maxLength={80} onChange={e=>update('account',e.target.value)}/></label><label>账户类型<select value={meta.accountType} onChange={e=>update('accountType',e.target.value)}><option value="">请选择，不能自动猜测</option><option value="seller">Seller 卖家 · 7 天归因</option><option value="vendor">Vendor 供应商 · 14 天归因</option></select></label><label>站点代码<input value={meta.marketplace} maxLength={2} onChange={e=>update('marketplace',e.target.value.toUpperCase())}/></label><label>币种<input value={meta.currency} maxLength={3} onChange={e=>update('currency',e.target.value.toUpperCase())}/></label><label>报表时区<input value={meta.timezone} onChange={e=>update('timezone',e.target.value)}/></label><label>数字格式<select value={meta.numberFormat} onChange={e=>update('numberFormat',e.target.value)}><option value="dot">1,234.56（点号为小数点）</option><option value="comma">1.234,56（逗号为小数点）</option></select></label><label>报表生成日期<input type="date" value={meta.asOf} onChange={e=>update('asOf',e.target.value)}/></label></div>
  <details open className="ai-mapping"><summary>字段映射 · 请核对自动识别结果</summary><div className="ai-form-grid">{Object.keys(FIELDS).map(k=><label key={k}>{LABELS[k]}<select value={mapping[k]||''} onChange={e=>{setMapping(m=>({...m,[k]:e.target.value}));setPreview(null);}}><option value="">未提供 / 未识别</option>{file.headers.map(h=><option key={h}>{h}</option>)}</select></label>)}</div></details>
  <p className="ai-muted">生成日期以文件修改日期为初值，请按实际报表生成日期核对。日期支持 YYYY-MM-DD、Excel 日期或美式 MM/DD/YYYY；其他日期格式请先转换。</p>
  <button className="ai-primary" disabled={working} onClick={()=>run(async()=>setPreview(await api().previewReport({id:file.id,mapping,metadata:meta})))}>{working?<LoaderCircle size={16} className="spin"/>:<FileSearch size={16}/>}检查数据并预览</button>
  {preview&&<section className="ai-import-preview"><h3>导入检查通过 · {preview.count} 行</h3><p>{preview.meta.marketplace} / {preview.meta.currency} / {preview.meta.timezone} · {preview.meta.attributionDays} 天归因 · 生成于 {preview.meta.asOf}</p><ul>{preview.warnings.map(w=><li key={w}>{w}</li>)}</ul><div className="ai-notice">{preview.duplicate?'这是重复文件，保存时会跳过。':preview.replaced?`将更新 ${preview.replaced} 条相同维度记录，保留自动备份；不会重复累计。`:'新记录将保存在本机 AI 数据目录。'}</div><div className="ai-table-scroll"><table><thead><tr><th>期间</th><th>活动 / 广告组</th><th>搜索词 / 投放 / 商品</th>{numberFields.map(k=><th key={k}>{LABELS[k]}</th>)}</tr></thead><tbody>{preview.rows.map((r,i)=><tr key={i}><td>{r.start}—{r.end}</td><td>{r.campaign} / {r.group}</td><td>{r.term||r.target||r.asin}</td>{numberFields.map(k=><td key={k}>{show(r[k])}</td>)}</tr>)}</tbody></table></div><p className="ai-muted">仅显示前 20 行；校验覆盖全部记录。空指标不会被自动填为零。</p><button className="ai-primary" disabled={working} onClick={()=>run(async()=>{await api().commitReport(preview.id);setFile(null);setPreview(null);onChanged();})}><CheckCircle2 size={16}/>确认保存报表</button></section>}
  </>}
  </section>;
}

export default function AIWorkspace({model,initialKeyword='',onClose}) {
  const [tab,setTab]=useState('analysis'),[status,setStatus]=useState({}),[reports,setReports]=useState({groups:[],batches:[]}),[history,setHistory]=useState([]);
  const latest=model?.latestDate||today();
  const [options,setOptions]=useState({mode:initialKeyword?'keyword':'product',keyword:initialKeyword,start:shift(latest,-29),end:latest,adGroup:'',targetAcos:'',eventDate:latest,eventType:'bid',eventNote:'',includeNotes:false});
  const [preview,setPreview]=useState(null),[confirmed,setConfirmed]=useState(false),[result,setResult]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(''),[highlight,setHighlight]=useState('');
  const closeRef=useRef(null);
  const refresh=async()=>{const [s,r,h]=await Promise.all([api().status(),api().reports(),api().history()]);setStatus(s);setReports(r);setHistory(h);};
  useEffect(()=>{const onConnection=()=>{setPreview(null);setConfirmed(false);setResult(null);refresh().catch(e=>setError(e.message));};window.addEventListener('keyword-ai-connection',onConnection);return()=>window.removeEventListener('keyword-ai-connection',onConnection);},[]);
  useEffect(()=>{const before=document.activeElement;closeRef.current?.focus();refresh().catch(e=>setError(e.message));api().preferences().then(p=>{if(p[model?.parentAsin])setOptions(o=>({...o,targetAcos:p[model.parentAsin].targetAcos}));}).catch(e=>setError(e.message));return()=>before?.focus?.();},[]);
  useEffect(()=>{const focus=()=>api().status().then(s=>{setStatus(s);setPreview(null);setConfirmed(false);}).catch(e=>setError(e.message));window.addEventListener('focus',focus);return()=>window.removeEventListener('focus',focus);},[]);
  const change=(key,value)=>{setOptions(o=>({...o,[key]:value,...(key==='mode'&&value==='review'?{eventDate:o.start}:{})}));setPreview(null);setConfirmed(false);};
  const run=async(label,fn)=>{setError('');setMessage('');setBusy(label);try{await fn();}catch(e){setError(e.message);}finally{setBusy('');}};
  const notes=useMemo(()=>(model?.matrixRows||[]).flatMap(row=>(model.dates||[]).flatMap((date,i)=>['natural','sp'].flatMap(metric=>{const note=row[metric==='natural'?'naturalAnnotations':'spAnnotations']?.[i];return note?[{keyword:row.keyword,date,text:note,metric}]:[];}))),[model?.matrixRows,model?.dates]);
  const input=()=>({...options,productId:model?.parentAsin||'',productName:model?.modelName||'',marketplace:model?.countryCode||'',records:(model?.historyRecords||[]).map(r=>({keyword:r.keyword,snapshotDate:r.snapshotDate,sourceFile:r.sourceFile,naturalRank:r.naturalRank,spRank:r.spRank,weeklyAbaRank:r.weeklyAbaRank,weeklySearchVolume:r.weeklySearchVolume,trafficShare:r.trafficShare}))});
  const focusEvidence=id=>{setHighlight(id);document.getElementById(`ai-${id}`)?.scrollIntoView({block:'center'});};
  const activePayload=result?.payload||preview?.payload;
  return <div className="ai-workspace" role="dialog" aria-modal="true" aria-label="AI 分析工作台" onKeyDown={e=>{if(e.key==='Escape'&&!busy){e.stopPropagation();onClose();}if(e.key==='Tab'){const els=[...e.currentTarget.querySelectorAll('button,input,select,summary,textarea,a[href]')].filter(el=>!el.disabled&&el.getClientRects().length);const first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}>
    <header className="ai-header"><div className="ai-heading"><button ref={closeRef} className="ai-back" disabled={!!busy} onClick={onClose}><ArrowLeft size={18}/>返回表格</button><div><h1>AI 分析工作台</h1><p>{model?`${model.modelName} · ${model.parentAsin}`:'尚未导入排名数据 · 可先导入广告报表'}</p></div></div><div className="ai-header-tools"><span className="ai-local"><ShieldCheck size={16}/>本机计算 · 手动执行</span><button disabled={!!busy} onClick={()=>run('正在打开设置…',async()=>api().settings())}><Settings2 size={16}/>安全设置</button></div></header>
    <nav className="ai-tabs" aria-label="分析工作台页面">{[['analysis','数据分析',Sparkles],['import','广告报表',Upload],['history','分析历史',History]].map(([key,label,Icon])=><button key={key} className={tab===key?'selected':''} disabled={!!busy} onClick={()=>{setTab(key);setError('');}}><Icon size={16}/>{label}{key==='history'&&history.length>0&&<span>{history.length}</span>}</button>)}</nav>
    <div className="ai-body" aria-busy={!!busy}>{error&&<div role="alert" className="ai-error"><AlertCircle size={18}/><span>{error}</span><button aria-label="关闭错误提示" onClick={()=>setError('')}><X size={16}/></button></div>}{message&&<div role="status" className="ai-notice"><CheckCircle2 size={18}/>{message}</div>}
      {api().kind==='web-connector'&&<section className={`ai-section ai-connector-status ${status.connected?'is-connected':''}`}><div className="ai-section-heading"><div><h2>{status.connected?'已连接本机安全连接器':'先连接本机安全连接器'}</h2><p>{status.connected?'排名直接读取当前网页；密钥由 Windows 加密保管。广告报表和分析历史保存在本机。':'首次使用：注册连接器 → 加载浏览器扩展 → 在扩展中点击“连接当前页面”。本地 HTML 需要开启扩展的“允许访问文件网址”。'}</p></div><button disabled={!!busy} onClick={()=>{api().checkConnection();refresh().catch(e=>setError(e.message));}}>检查连接</button></div>{!status.connected&&<details><summary>查看安装与连接步骤</summary><ol><li>把随包的“AI本机连接器”文件夹放到固定位置，运行 KeywordRankAIConnector.exe，选择“注册连接器”。</li><li>打开 Chrome / Edge 的扩展管理页，开启开发者模式，“加载已解压的扩展”，选择随包“AI浏览器扩展”文件夹。</li><li>在扩展详情开启“允许访问文件网址”，回到关键词网页，在扩展中点击“连接当前页面”。</li><li>核对本机确认窗口中的页面地址，允许后在此页打开“安全设置”填写 API。</li></ol><p>每次刷新网页需重新连接；无需迁移原网页排名数据。完整步骤见随包《网页版AI使用说明》。</p></details>}{status.error&&<p role="status">{status.error}</p>}</section>}
      {tab==='import'&&<><ImportPanel onError={setError} onChanged={()=>{setMessage('广告报表已保存。');setPreview(null);refresh().catch(e=>setError(e.message));}}/><section className="ai-section"><div className="ai-section-heading"><h2>已保存报表 · {reports.batches.length} 批</h2><div className="ai-actions"><button onClick={()=>run('正在导出…',async()=>{if(await api().backup())setMessage('广告和分析备份已导出，不含密钥。');})}>导出广告与分析备份</button><button onClick={()=>run('正在恢复…',async()=>{if(await api().restore()){await refresh();setMessage('备份已恢复。');}})}>恢复备份</button></div></div><div className="ai-table-scroll"><table><thead><tr><th>来源文件</th><th>账户 / 站点</th><th>类型</th><th>行数</th><th>币种 / 归因</th><th>生成日期</th></tr></thead><tbody>{reports.batches.map(b=><tr key={b.id}><td>{b.filename}</td><td>{b.meta.account} / {b.meta.marketplace}</td><td>{TYPES[b.meta.type]}</td><td>{b.count}</td><td>{b.meta.currency} / {b.meta.attributionDays} 天</td><td>{b.meta.asOf}</td></tr>)}</tbody></table></div></section></>}
      {tab==='history'&&<section className="ai-section"><h2>本地分析历史</h2><p>保留最近 50 次成功分析；历史报告使用当时的数据快照。不会自动重新请求平台。</p>{!history.length?<div className="ai-empty"><History size={32}/><h3>还没有分析记录</h3><p>完成首次分析后，报告和证据会保存在这里。</p></div>:<div className="ai-table-scroll"><table><thead><tr><th>时间</th><th>商品 / 关键词</th><th>分析期间</th><th>类型</th><th>模型 / 平台</th><th>操作</th></tr></thead><tbody>{history.map(h=><tr key={h.id}><td>{new Date(h.createdAt).toLocaleString()}</td><td>{h.localContext?.productName||'未关联商品'}<small>{h.localContext?.keyword||h.localContext?.productId||'广告组分析'}</small></td><td>{h.payload.period.start}—{h.payload.period.end}</td><td>{{product:'商品',keyword:'关键词',review:'操作复盘'}[h.payload.mode]}</td><td>{h.model}<small>{h.endpoint}</small></td><td><button onClick={()=>{setResult(h);setPreview(null);setTab('analysis');}}>查看报告</button></td></tr>)}</tbody></table></div>}</section>}
      {tab==='analysis'&&<>
        <section className="ai-section"><div className="ai-section-heading"><div><h2>1. 选择分析范围</h2><p>本机先计算指标，AI 再解释证据。广告数据使用所选广告组整体口径。</p></div><span className={`ai-connection ${status.configured?'ready':''}`}>{status.configured?'已配置连接':'尚未配置连接'}</span></div>
          <fieldset disabled={!!busy} className="ai-fieldset"><div className="ai-form-grid"><label>分析类型<select value={options.mode} onChange={e=>change('mode',e.target.value)}><option value="product">商品综合分析</option><option value="keyword">单个关键词分析</option><option value="review">操作前后复盘</option></select></label><label>关键词{options.mode==='keyword'?'（必填）':'（可留空）'}<input list="ai-keywords" placeholder="全部关键词" value={options.keyword} onChange={e=>change('keyword',e.target.value)}/><datalist id="ai-keywords">{(model?.matrixRows||[]).map(r=><option key={r.keyword} value={r.keyword}/>)}</datalist></label><label>本期开始<input type="date" value={options.start} onChange={e=>{change('start',e.target.value);if(options.mode==='review')change('eventDate',e.target.value);}}/></label><label>本期结束<input type="date" value={options.end} onChange={e=>change('end',e.target.value)}/></label><label className="ai-wide">广告组与报表视角<select value={options.adGroup} onChange={e=>change('adGroup',e.target.value)}><option value="">不使用广告数据 · 仅分析排名</option>{reports.groups.map(g=><option key={g.key} value={g.key}>{g.label}</option>)}</select></label><label>商品目标 ACOS（%）<input type="number" min="0.01" max="1000" step="0.1" value={options.targetAcos} placeholder="选填，不设统一标准" onChange={e=>change('targetAcos',e.target.value)}/></label></div><div className="ai-actions"><span className="ai-muted">快捷期间</span>{[7,30].map(n=><button key={n} onClick={()=>{change('start',shift(latest,1-n));change('end',latest);if(options.mode==='review')change('eventDate',shift(latest,1-n));}}>最近 {n} 天</button>)}<span className="ai-muted">与前一个等长区间比较 · 默认结束于最新排名日期</span></div>
          {options.mode==='review'&&<div className="ai-review"><h3>操作信息</h3><div className="ai-form-grid"><label>选择已有标注<select defaultValue="" onChange={e=>{const n=notes[Number(e.target.value)];if(n){setOptions(o=>({...o,start:n.date,end:shift(n.date,29),eventDate:n.date,keyword:n.keyword,eventNote:n.text}));setPreview(null);setConfirmed(false);}}}><option value="" disabled>也可手动填写</option>{notes.map((n,i)=><option value={i} key={i}>{n.date} · {n.keyword} · {n.text.slice(0,50)}</option>)}</select></label><label>操作类型<select value={options.eventType} onChange={e=>change('eventType',e.target.value)}><option value="bid">投放 / 竞价调整</option><option value="price">价格调整</option><option value="listing">Listing 修改</option><option value="other">其他操作</option></select></label><label>操作日期<input type="date" value={options.eventDate} onChange={e=>{change('eventDate',e.target.value);change('start',e.target.value);}}/></label></div><label>操作备注<textarea maxLength={1500} value={options.eventNote} onChange={e=>change('eventNote',e.target.value)}/></label><label className="ai-check"><input type="checkbox" checked={options.includeNotes} onChange={e=>change('includeNotes',e.target.checked)}/>将本条备注发给 AI（默认关闭；请先移除敏感信息）</label></div>}
          </fieldset><div className="ai-actions ai-form-actions"><button className="ai-primary" disabled={!!busy||!status.configured} onClick={()=>run('正在本机检查数据…',async()=>{setResult(null);const p=await api().prepare(input());setPreview(p);setConfirmed(false);})}><FileSearch size={16}/>检查数据与发送预览</button><button disabled={!!busy||!status.configured} onClick={()=>run('正在测试连接…',async()=>{const r=await api().test();setMessage(r.message);})}>仅测试连接</button><span className="ai-muted">测试会向已配置平台发送固定文本，可能产生少量费用。</span></div>
        </section>
        {preview&&!result&&<section className="ai-section"><h2>2. 核对发送内容</h2><div className="ai-notice"><ShieldCheck size={20}/><span>目的地：<b>{new URL(preview.endpoint).hostname}</b> · 模型：{preview.model}<br/>发送 {preview.payload.evidence.length} 条摘要证据。商品和活动使用代号；关键词及经营指标仍可能透露业务信息。</span></div><p>本期：{preview.payload.period.start}—{preview.payload.period.end}　对比：{preview.payload.period.previousStart}—{preview.payload.period.previousEnd}</p><ul className="ai-limitations">{preview.payload.limitations.map(l=><li key={l}>{l}</li>)}</ul><details><summary>查看实际请求正文（不包含密钥）</summary><pre className="ai-request">{JSON.stringify(preview.request,null,2)}</pre></details><label className="ai-check"><input type="checkbox" checked={confirmed} disabled={!!busy} onChange={e=>setConfirmed(e.target.checked)}/>我已核对目的地和内容，同意将这些数据发送给该平台</label><button className="ai-primary" disabled={!!busy||!confirmed} onClick={()=>run('AI 正在分析证据…',async()=>{const id=preview.id;setPreview(null);setConfirmed(false);const r=await api().start(id);setResult(r);await refresh();})}><Sparkles size={16}/>发送并分析</button><span className="ai-muted ai-inline">费用以平台账单为准，不自动重试。</span></section>}
        {result&&<section className="ai-section ai-report"><div className="ai-section-heading"><div><h2>分析报告</h2><p>{result.localContext?.productName||'未关联商品'} · {new Date(result.createdAt).toLocaleString()} · {result.model} · {result.payload.period.start}—{result.payload.period.end}</p></div><span className="ai-local">建议需人工评估</span></div><div className="ai-notice">以下为 AI 对证据的解释，可能存在错误；请展开来源核对。假设不代表已证实的原因。</div>{result.result.findings.map((f,i)=><article key={i} className="ai-finding"><div className="ai-finding-title"><span>{String(i+1).padStart(2,'0')}</span><h3>{f.title}</h3></div><dl><dt>事实</dt><dd>{f.fact}</dd><dt>可能原因 · 推测</dt><dd>{f.hypothesis}</dd><dt>建议核查</dt><dd>{f.action}</dd></dl><div className="ai-actions"><span className="ai-muted">依据</span>{f.evidenceIds.map(id=><button key={id} onClick={()=>focusEvidence(id)}>{id} · 查看证据</button>)}</div></article>)}<h3>数据限制</h3><ul className="ai-limitations">{[...result.payload.limitations,...result.result.limitations].map((l,i)=><li key={i}>{l}</li>)}</ul></section>}
        {activePayload&&<section className="ai-section"><div className="ai-section-heading"><h2>证据表 · {activePayload.evidence.length} 条</h2><span className="ai-muted">{activePayload.adScope && `${activePayload.adScope.marketplace} · ${activePayload.adScope.currency} · ${activePayload.adScope.attributionDays} 天归因 · `}“—”表示未提供或无法计算</span></div><MetricTable evidence={activePayload.evidence} sources={result?.sources||preview?.sources} highlight={highlight}/></section>}
        {!preview&&!result&&<div className="ai-empty ai-first"><Sparkles size={32}/><h3>每条建议，都能回到数据</h3><p>排名趋势、广告效率和潜力词一起查看。缺少数据时，会明确告诉你还需要什么。</p></div>}
      </>}
    </div>
    <footer className="ai-footer"><span><ShieldCheck size={14}/>密钥不进入业务备份 · 无自动广告操作</span>{busy?<div role="status"><LoaderCircle size={15} className="spin"/>{busy}<button onClick={()=>api().cancel().catch(e=>setError(e.message))}>取消请求</button></div>:<span>{api().kind==='web-connector'?'网页版 · 排名保留在原网页，AI 数据保存在本机':'本机增强版 · 业务数据保存在独立目录'}</span>}</footer>
  </div>;
}
